spring:
  cloud:
    gateway:
      routes:
        - id: javaboy_route
          uri: lb://provider  #\u4F1A\u81EA\u52A8\u4ECEEureka\u4E2D\u5BFB\u627Eprovider\u7684\u670D\u52A1\u4EE3\u7406
          filters:
            - AddRequestParameter=name,javaboy  # \u53C2\u6570\u540D\uFF0C\u53C2\u6570value
          predicates:
            - After=2022-07-06T01:01:01+08:00[Asia/Shanghai]
#            - Path=/get
            - Method=GET
#            - Query=name,java.* #key:name value:\u4EE5java\u5F00\u59CB
      discovery:
        locator:
          enabled: true  #\u5F00\u542F\u81EA\u52A8\u4EE3\u7406
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
#\u65E5\u5FD7\u914D\u7F6E
logging:
  level:
    org.springframework.cloud.gateway: debug